# Generated by Django 6.0.5 on 2026-06-10 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, verbose_name='Şube Adı')),
                ('depo_mu', models.BooleanField(default=False, help_text="İşaretliyse bu şube vardiya planına dahil edilmez (eski 'GEEK DEPO' mantığının yerini alır).", verbose_name='Depo mu?')),
            ],
            options={
                'verbose_name': 'Şube',
                'verbose_name_plural': 'Şubeler',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='Personel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('rol', models.CharField(choices=[('Genel Müdür', 'Genel Müdür (Tam Yetkili)'), ('Müdür', 'Bölge Müdürü (Tam Yetkili)'), ('Operatör', 'Operatör (Tam Yetkili)'), ('Şef', 'Şube Şefi'), ('Personel', 'Personel')], default='Personel', max_length=20, verbose_name='Rol')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personel', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı Hesabı')),
                ('sube', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personeller', to='panel.sube', verbose_name='Şubesi')),
            ],
            options={
                'verbose_name': 'Personel',
                'verbose_name_plural': 'Personeller',
                'ordering': ['ad_soyad'],
            },
        ),
        migrations.CreateModel(
            name='Mola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(blank=True, null=True, verbose_name='Mola Tarihi')),
                ('mola_tipi', models.CharField(default='1. Mola', max_length=20, verbose_name='Mola Tipi')),
                ('baslangic_saati', models.TimeField(blank=True, null=True, verbose_name='Başlangıç Saati')),
                ('bitis_saati', models.TimeField(blank=True, null=True, verbose_name='Bitiş Saati')),
                ('personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='molalar', to='panel.personel')),
            ],
            options={
                'verbose_name': 'Mola',
                'verbose_name_plural': 'Molalar',
                'ordering': ['-tarih', '-baslangic_saati'],
            },
        ),
        migrations.CreateModel(
            name='Puantaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ay', models.DateField(verbose_name='Puantaj Ayı')),
                ('calisilan_gun', models.IntegerField(default=0, verbose_name='Çalışılan Gün')),
                ('eksik_gun', models.IntegerField(default=0, verbose_name='Eksik Gün')),
                ('izinli_gun', models.IntegerField(default=0, verbose_name='İzinli Gün')),
                ('raporlu_gun', models.IntegerField(default=0, verbose_name='Raporlu Gün')),
                ('manuel_duzenlendi', models.BooleanField(default=False, verbose_name='Manuel Düzenlendi mi?')),
                ('personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puantajlar', to='panel.personel')),
            ],
            options={
                'verbose_name': 'Puantaj',
                'verbose_name_plural': 'Puantajlar',
                'ordering': ['-ay'],
                'constraints': [models.UniqueConstraint(fields=('personel', 'ay'), name='unique_personel_ay_puantaj')],
            },
        ),
        migrations.CreateModel(
            name='Vardiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(verbose_name='Vardiya Tarihi')),
                ('vardiya_tipi', models.CharField(choices=[('Sabahçı', 'Sabahçı'), ('Aracı', 'Aracı'), ('Akşamcı', 'Akşamcı'), ('İzinli', 'İzinli'), ('Raporlu', 'Raporlu'), ('Devamsız', 'Devamsız')], default='Sabahçı', max_length=20, verbose_name='Vardiya Tipi')),
                ('notlar', models.TextField(blank=True, null=True, verbose_name='Personel Notu / Mazeret')),
                ('durum', models.CharField(choices=[('Taslak', 'Taslak'), ('Onay Bekliyor', 'Onay Bekliyor'), ('Onaylandı', 'Onaylandı'), ('Reddedildi', 'Reddedildi')], default='Taslak', max_length=20, verbose_name='Onay Durumu')),
                ('red_notu', models.TextField(blank=True, null=True, verbose_name='Red Notu')),
                ('personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vardiyalar', to='panel.personel')),
            ],
            options={
                'verbose_name': 'Vardiya',
                'verbose_name_plural': 'Vardiyalar',
                'ordering': ['tarih'],
                'constraints': [models.UniqueConstraint(fields=('personel', 'tarih'), name='unique_personel_tarih_vardiya')],
            },
        ),
    ]
