# Generated by Django 6.0.5 on 2026-06-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KodKilit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=45, unique=True, verbose_name='IP Adresi')),
                ('hatali_deneme', models.IntegerField(default=0)),
                ('kilit_bitis', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Kod Giriş Kilidi',
                'verbose_name_plural': 'Kod Giriş Kilitleri',
            },
        ),
        migrations.AddField(
            model_name='personel',
            name='giris_kodu',
            field=models.CharField(blank=True, help_text='Personel rolündekilerin sisteme giriş için kullandığı 6 haneli kod.', max_length=6, null=True, unique=True, verbose_name='Giriş Kodu'),
        ),
        migrations.AlterField(
            model_name='sube',
            name='depo_mu',
            field=models.BooleanField(default=False, help_text='İşaretliyse bu şube vardiya planına dahil edilmez.', verbose_name='Depo mu?'),
        ),
    ]
