# Generated by Django 6.0.5 on 2026-06-11 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_kodkilit_personel_giris_kodu_alter_sube_depo_mu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zayi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giren_ad', models.CharField(blank=True, max_length=100, verbose_name='Giren (ad)')),
                ('urun_adi', models.CharField(max_length=120, verbose_name='Ürün Adı')),
                ('miktar', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Miktar')),
                ('birim', models.CharField(choices=[('adet', 'adet'), ('ml', 'ml')], default='adet', max_length=10, verbose_name='Birim')),
                ('olusturma', models.DateTimeField(auto_now_add=True, verbose_name='Girildiği An')),
                ('giren', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zayi_girisleri', to='panel.personel', verbose_name='Giren Personel')),
                ('sube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zayiler', to='panel.sube', verbose_name='Şube')),
            ],
            options={
                'verbose_name': 'Zayi',
                'verbose_name_plural': 'Zayiler',
                'ordering': ['-olusturma'],
            },
        ),
    ]
