# Generated by Django 6.0.5 on 2026-06-11 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_zayi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kalibrasyon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giren_ad', models.CharField(blank=True, max_length=100, verbose_name='Yükleyen (ad)')),
                ('foto', models.FileField(upload_to='kalibrasyon/%Y/%m/%d/', verbose_name='Görüntü')),
                ('olusturma', models.DateTimeField(auto_now_add=True, verbose_name='Yüklendiği An')),
                ('giren', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kalibrasyonlar', to='panel.personel', verbose_name='Yükleyen')),
                ('sube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kalibrasyonlar', to='panel.sube', verbose_name='Şube')),
            ],
            options={
                'verbose_name': 'Kalibrasyon',
                'verbose_name_plural': 'Kalibrasyonlar',
                'ordering': ['-olusturma'],
            },
        ),
    ]
