# Generated by Django 6.0.5 on 2026-06-12 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_kalibrasyon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personel',
            name='rol',
            field=models.CharField(choices=[('Genel Müdür', 'Genel Müdür (Tam Yetkili)'), ('Müdür', 'Bölge Müdürü (Tam Yetkili)'), ('Operatör', 'Operatör (Tam Yetkili)'), ('Satın Alma', 'Satın Alma'), ('Sevkiyat', 'Sevkiyat'), ('Şef', 'Şube Şefi'), ('Personel', 'Personel')], default='Personel', max_length=20, verbose_name='Rol'),
        ),
        migrations.CreateModel(
            name='SevkiyatTalep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturan_ad', models.CharField(blank=True, max_length=100)),
                ('durum', models.CharField(choices=[('Talep', 'Talep (Satın Alma bekliyor)'), ('Sevkiyatta', 'Sevkiyatta (Teslim bekliyor)'), ('Teslim Edildi', 'Teslim Edildi')], default='Talep', max_length=20, verbose_name='Durum')),
                ('not_metni', models.CharField(blank=True, max_length=300, verbose_name='Not')),
                ('satin_alan_ad', models.CharField(blank=True, max_length=100)),
                ('teslim_eden_ad', models.CharField(blank=True, max_length=100)),
                ('olusturma', models.DateTimeField(auto_now_add=True, verbose_name='Talep Tarihi')),
                ('satin_alma_tarih', models.DateTimeField(blank=True, null=True, verbose_name='Satın Alma Tarihi')),
                ('teslim_tarih', models.DateTimeField(blank=True, null=True, verbose_name='Teslim Tarihi')),
                ('olusturan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sevkiyat_talepleri', to='panel.personel', verbose_name='Oluşturan')),
                ('sube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sevkiyat_talepleri', to='panel.sube', verbose_name='Şube')),
            ],
            options={
                'verbose_name': 'Sevkiyat Talebi',
                'verbose_name_plural': 'Sevkiyat Talepleri',
                'ordering': ['-olusturma'],
            },
        ),
        migrations.CreateModel(
            name='SevkiyatKalem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urun_adi', models.CharField(max_length=120, verbose_name='Ürün Adı')),
                ('istenen', models.PositiveIntegerField(verbose_name='İstenen')),
                ('verilen', models.PositiveIntegerField(blank=True, null=True, verbose_name='Verilen')),
                ('birim', models.CharField(choices=[('adet', 'adet'), ('koli', 'koli')], default='adet', max_length=10, verbose_name='Birim')),
                ('talep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kalemler', to='panel.sevkiyattalep')),
            ],
        ),
    ]
