# Generated by Django 6.0.5 on 2026-06-15 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_alter_personel_rol_sevkiyattalep_sevkiyatkalem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(choices=[('HAMMADDE', 'Hammadde'), ('TEMIZLIK', 'Temizlik')], default='HAMMADDE', max_length=10, verbose_name='Form')),
                ('kategori', models.CharField(max_length=80, verbose_name='Kategori')),
                ('ad', models.CharField(max_length=160, verbose_name='Ürün Adı')),
                ('koli_icerigi', models.PositiveIntegerField(default=1, verbose_name='Koli İçeriği')),
                ('birim', models.CharField(choices=[('ADET', 'ADET'), ('KOLİ', 'KOLİ'), ('KG', 'KG'), ('GRAM', 'GRAM'), ('LİTRE', 'LİTRE'), ('ML', 'ML'), ('PAKET', 'PAKET'), ('SET', 'SET')], default='ADET', max_length=10, verbose_name='Birim')),
                ('sira', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Ürün (Katalog)',
                'verbose_name_plural': 'Ürünler (Katalog)',
                'ordering': ['form', 'sira', 'ad'],
            },
        ),
        migrations.AlterModelOptions(
            name='sevkiyatkalem',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='sevkiyattalep',
            options={'ordering': ['-olusturma'], 'verbose_name': 'Sevkiyat Siparişi', 'verbose_name_plural': 'Sevkiyat Siparişleri'},
        ),
        migrations.RemoveField(
            model_name='sevkiyatkalem',
            name='birim',
        ),
        migrations.RemoveField(
            model_name='sevkiyatkalem',
            name='istenen',
        ),
        migrations.RemoveField(
            model_name='sevkiyatkalem',
            name='urun_adi',
        ),
        migrations.RemoveField(
            model_name='sevkiyatkalem',
            name='verilen',
        ),
        migrations.RemoveField(
            model_name='sevkiyattalep',
            name='teslim_eden_ad',
        ),
        migrations.RemoveField(
            model_name='sevkiyattalep',
            name='teslim_tarih',
        ),
        migrations.AddField(
            model_name='sevkiyatkalem',
            name='form',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='sevkiyatkalem',
            name='istenen_birim',
            field=models.CharField(default='ADET', max_length=10),
        ),
        migrations.AddField(
            model_name='sevkiyatkalem',
            name='istenen_miktar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sevkiyatkalem',
            name='kategori',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='sevkiyatkalem',
            name='koli_icerigi',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sevkiyatkalem',
            name='satinalma_birim',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='sevkiyatkalem',
            name='satinalma_miktar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sevkiyatkalem',
            name='sevkiyat_birim',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='sevkiyatkalem',
            name='sevkiyat_miktar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sevkiyatkalem',
            name='urun_ad',
            field=models.CharField(default=0, max_length=160),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sevkiyattalep',
            name='onay_tarih',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sevkiyattalep',
            name='onaylayan_ad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sevkiyattalep',
            name='red_notu',
            field=models.CharField(blank=True, max_length=400, verbose_name='Red Açıklaması'),
        ),
        migrations.AddField(
            model_name='sevkiyattalep',
            name='sevkiyat_tarih',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sevkiyattalep',
            name='sevkiyatci_ad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sevkiyattalep',
            name='durum',
            field=models.CharField(choices=[('Talep', 'Satın Almada'), ('Sevkiyatta', 'Sevkiyatta'), ('Onay Bekliyor', 'Çıkış Onayı Bekliyor'), ('Onaylandı', 'Onaylandı'), ('Reddedildi', 'Reddedildi (Düzeltmede)'), ('Teslim Edildi', 'Teslim Edildi')], default='Talep', max_length=20, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='sevkiyattalep',
            name='not_metni',
            field=models.CharField(blank=True, max_length=400, verbose_name='Şef Notu'),
        ),
        migrations.AlterField(
            model_name='sevkiyattalep',
            name='olusturma',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Sipariş Tarihi'),
        ),
        migrations.AlterField(
            model_name='sevkiyattalep',
            name='satin_alma_tarih',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SiparisHareket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesaj', models.CharField(max_length=200)),
                ('aciklama', models.CharField(blank=True, max_length=400)),
                ('yapan_ad', models.CharField(blank=True, max_length=100)),
                ('olusturma', models.DateTimeField(auto_now_add=True)),
                ('talep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hareketler', to='panel.sevkiyattalep')),
            ],
            options={
                'ordering': ['olusturma'],
            },
        ),
        migrations.AddField(
            model_name='sevkiyatkalem',
            name='urun',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='panel.urun'),
        ),
    ]
