# Generated by Django 6.0.5 on 2026-06-16 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_urun_alter_sevkiyatkalem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sevkiyatkalem',
            name='form',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='sevkiyatkalem',
            name='istenen_miktar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sevkiyatkalem',
            name='kategori',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='sevkiyatkalem',
            name='satinalma_birim',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='sevkiyatkalem',
            name='sevkiyat_birim',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='sevkiyatkalem',
            name='urun_ad',
            field=models.CharField(default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='sevkiyattalep',
            name='onaylayan_ad',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sevkiyattalep',
            name='red_notu',
            field=models.CharField(blank=True, default='', max_length=400, verbose_name='Red Açıklaması'),
        ),
        migrations.AlterField(
            model_name='sevkiyattalep',
            name='satin_alan_ad',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sevkiyattalep',
            name='sevkiyatci_ad',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='Irsaliye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giren_ad', models.CharField(blank=True, max_length=100, verbose_name='Yükleyen (ad)')),
                ('foto', models.FileField(upload_to='irsaliye/%Y/%m/%d/', verbose_name='Görüntü')),
                ('aciklama', models.TextField(verbose_name='Açıklama')),
                ('olusturma', models.DateTimeField(auto_now_add=True, verbose_name='Yüklendiği An')),
                ('giren', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='irsaliyeler', to='panel.personel', verbose_name='Yükleyen')),
            ],
            options={
                'verbose_name': 'İrsaliye / Transfer',
                'verbose_name_plural': 'İrsaliye / Transferler',
                'ordering': ['-olusturma'],
            },
        ),
    ]
