# Generated by Django 6.0.5 on 2026-06-17 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_alter_sevkiyatkalem_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personel',
            name='sorumlu_subeler',
            field=models.ManyToManyField(blank=True, related_name='bolge_mudurleri', to='panel.sube', verbose_name='Sorumlu olduğu şubeler (Bölge Müdürü)'),
        ),
    ]
