# Generated by Django 6.0.5 on 2026-06-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0008_personel_sorumlu_subeler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personel',
            name='rol',
            field=models.CharField(choices=[('Genel Müdür', 'Genel Müdür (Tam Yetkili)'), ('Müdür', 'Bölge Müdürü'), ('Operatör', 'Operatör (Tam Yetkili)'), ('Yatırımcı', 'Yatırımcı (Tam Yetkili)'), ('Satın Alma', 'Satın Alma'), ('Sevkiyat', 'Sevkiyat'), ('Şef', 'Şube Şefi'), ('Personel', 'Personel')], default='Personel', max_length=20, verbose_name='Rol'),
        ),
    ]
