# Generated by Django 6.0.5 on 2026-06-17 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0009_alter_personel_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='StokUrun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(blank=True, max_length=80, verbose_name='Kategori')),
                ('ad', models.CharField(max_length=160, verbose_name='Ürün Adı')),
                ('birim', models.CharField(default='adet', max_length=20, verbose_name='Birim')),
                ('sira', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Stok Kalemi (Katalog)',
                'verbose_name_plural': 'Stok Kalemleri (Katalog)',
                'ordering': ['kategori', 'sira', 'ad'],
            },
        ),
        migrations.CreateModel(
            name='StokSayim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ay', models.DateField(verbose_name="Ay (ayın 1'i)")),
                ('giren_ad', models.CharField(blank=True, max_length=100, verbose_name='Giren (ad)')),
                ('olusturma', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma')),
                ('guncelleme', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme')),
                ('giren', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stok_sayimlari', to='panel.personel', verbose_name='Giren')),
                ('sube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stok_sayimlari', to='panel.sube', verbose_name='Şube')),
            ],
            options={
                'verbose_name': 'Stok Sayımı',
                'verbose_name_plural': 'Stok Sayımları',
                'ordering': ['-ay'],
                'unique_together': {('sube', 'ay')},
            },
        ),
        migrations.CreateModel(
            name='StokSayimKalem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urun_ad', models.CharField(max_length=160, verbose_name='Ürün Adı')),
                ('kategori', models.CharField(blank=True, max_length=80, verbose_name='Kategori')),
                ('birim', models.CharField(blank=True, max_length=20, verbose_name='Birim')),
                ('miktar', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Sayılan Miktar')),
                ('sayim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kalemler', to='panel.stoksayim')),
                ('urun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='panel.stokurun')),
            ],
            options={
                'verbose_name': 'Stok Sayım Kalemi',
                'verbose_name_plural': 'Stok Sayım Kalemleri',
                'ordering': ['kategori', 'urun_ad'],
            },
        ),
    ]
