# Generated by Django 6.0.5 on 2026-06-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0010_stokurun_stoksayim_stoksayimkalem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stoksayimkalem',
            options={'ordering': ['id'], 'verbose_name': 'Stok Sayım Kalemi', 'verbose_name_plural': 'Stok Sayım Kalemleri'},
        ),
        migrations.AlterModelOptions(
            name='stokurun',
            options={'ordering': ['sira', 'ad'], 'verbose_name': 'Stok Kalemi (Katalog)', 'verbose_name_plural': 'Stok Kalemleri (Katalog)'},
        ),
        migrations.RemoveField(
            model_name='stoksayimkalem',
            name='birim',
        ),
        migrations.RemoveField(
            model_name='stoksayimkalem',
            name='miktar',
        ),
        migrations.RemoveField(
            model_name='stokurun',
            name='birim',
        ),
        migrations.AddField(
            model_name='stoksayimkalem',
            name='acik_carpan',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='Açık çarpan'),
        ),
        migrations.AddField(
            model_name='stoksayimkalem',
            name='acik_miktar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Açık kutu miktarı'),
        ),
        migrations.AddField(
            model_name='stoksayimkalem',
            name='aciklama',
            field=models.CharField(blank=True, max_length=300, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='stoksayimkalem',
            name='kapali_adet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Kapalı kutu adedi'),
        ),
        migrations.AddField(
            model_name='stoksayimkalem',
            name='kapali_icerik',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='Kapalı içerik'),
        ),
        migrations.AddField(
            model_name='stokurun',
            name='acik_carpan',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='Açık kutu çarpanı'),
        ),
        migrations.AddField(
            model_name='stokurun',
            name='kapali_icerik',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='Kapalı kutu içeriği (adet/ml/kg)'),
        ),
        migrations.AlterField(
            model_name='stoksayimkalem',
            name='kategori',
            field=models.CharField(blank=True, max_length=80, verbose_name='Grup'),
        ),
        migrations.AlterField(
            model_name='stoksayimkalem',
            name='urun_ad',
            field=models.CharField(max_length=200, verbose_name='Ürün Adı'),
        ),
        migrations.AlterField(
            model_name='stokurun',
            name='ad',
            field=models.CharField(max_length=200, verbose_name='Ürün Adı'),
        ),
        migrations.AlterField(
            model_name='stokurun',
            name='kategori',
            field=models.CharField(blank=True, max_length=80, verbose_name='Grup'),
        ),
    ]
