# Generated by Django 6.0.5 on 2026-06-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0011_alter_stoksayimkalem_options_alter_stokurun_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='ust_birim',
            field=models.CharField(blank=True, choices=[('ADET', 'ADET'), ('KOLİ', 'KOLİ'), ('KG', 'KG'), ('GRAM', 'GRAM'), ('LİTRE', 'LİTRE'), ('ML', 'ML'), ('PAKET', 'PAKET'), ('SET', 'SET'), ('KUTU', 'KUTU')], default='KOLİ', max_length=10, verbose_name='Üst Birim (koli/paket/set; boş = yok)'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='birim',
            field=models.CharField(choices=[('ADET', 'ADET'), ('KOLİ', 'KOLİ'), ('KG', 'KG'), ('GRAM', 'GRAM'), ('LİTRE', 'LİTRE'), ('ML', 'ML'), ('PAKET', 'PAKET'), ('SET', 'SET'), ('KUTU', 'KUTU')], default='ADET', max_length=10, verbose_name='Taban Birim'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='koli_icerigi',
            field=models.PositiveIntegerField(default=1, verbose_name='İçerik (üst birimdeki taban birim adedi)'),
        ),
    ]
