# Generated by Django 6.0.5 on 2026-06-18 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0012_urun_ust_birim_alter_urun_birim_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KahveSoru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(blank=True, max_length=40)),
                ('metin', models.TextField(verbose_name='Soru')),
                ('sik_a', models.CharField(max_length=200)),
                ('sik_b', models.CharField(max_length=200)),
                ('sik_c', models.CharField(max_length=200)),
                ('sik_d', models.CharField(max_length=200)),
                ('dogru', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('aktif', models.BooleanField(default=True)),
                ('olusturma', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GunlukSoru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sube_ad', models.CharField(blank=True, max_length=120)),
                ('tarih', models.DateField()),
                ('baslangic', models.DateTimeField(blank=True, null=True)),
                ('secilen', models.CharField(blank=True, max_length=1)),
                ('dogru_mu', models.BooleanField(default=False)),
                ('sure_doldu', models.BooleanField(default=False)),
                ('cevaplandi', models.BooleanField(default=False)),
                ('olusturma', models.DateTimeField(auto_now_add=True)),
                ('personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gunluk_sorular', to='panel.personel')),
                ('sube', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='panel.sube')),
                ('soru', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='panel.kahvesoru')),
            ],
            options={
                'ordering': ['-tarih', 'personel'],
                'unique_together': {('personel', 'tarih')},
            },
        ),
    ]
