# Generated by Django 6.0.5 on 2026-06-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0013_kahvesoru_gunluksoru'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoruAyar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktif', models.BooleanField(default=False, verbose_name='Günlük soru sistemi aktif')),
                ('guncelleme', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Soru Sistemi Ayarı',
                'verbose_name_plural': 'Soru Sistemi Ayarı',
            },
        ),
        migrations.AlterField(
            model_name='personel',
            name='rol',
            field=models.CharField(choices=[('Genel Müdür', 'Genel Müdür (Tam Yetkili)'), ('Müdür', 'Bölge Müdürü'), ('Operatör', 'Operatör (Tam Yetkili)'), ('Yatırımcı', 'Yatırımcı (Tam Yetkili)'), ('Satın Alma', 'Satın Alma'), ('Sevkiyat', 'Sevkiyat'), ('Eğitmen', 'Eğitmen'), ('Şef', 'Şube Şefi'), ('Personel', 'Personel')], default='Personel', max_length=20, verbose_name='Rol'),
        ),
    ]
