# Generated by Django 6.0.5 on 2026-06-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0014_soruayar_alter_personel_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='personel',
            name='egitmen',
            field=models.BooleanField(default=False, help_text='İşaretliyse bu kişi (rolü ne olursa olsun) soru yönetimi ve bilgi karnesine erişir.', verbose_name='Eğitmen yetkisi'),
        ),
    ]
