# Generated by Django 6.0.5 on 2026-06-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0015_personel_egitmen'),
    ]

    operations = [
        migrations.AddField(
            model_name='sevkiyatkalem',
            name='hazirlandi',
            field=models.BooleanField(default=False),
        ),
    ]
