# Generated by Django 6.0.5 on 2026-06-23 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0016_sevkiyatkalem_hazirlandi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bildirim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesaj', models.CharField(max_length=200)),
                ('link', models.CharField(blank=True, default='', max_length=200)),
                ('tur', models.CharField(blank=True, default='', max_length=20)),
                ('okundu', models.BooleanField(default=False)),
                ('olusturma', models.DateTimeField(auto_now_add=True)),
                ('alici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bildirimler', to='panel.personel')),
            ],
            options={
                'ordering': ['-olusturma'],
                'indexes': [models.Index(fields=['alici', 'okundu'], name='panel_bildi_alici_i_6e73a0_idx')],
            },
        ),
    ]
