# Generated by Django 6.0.5 on 2026-06-23 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0017_bildirim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duyuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=150)),
                ('icerik', models.TextField()),
                ('yayinlayan_ad', models.CharField(blank=True, default='', max_length=120)),
                ('hedef_rol', models.CharField(blank=True, default='', max_length=20)),
                ('aktif', models.BooleanField(default=True)),
                ('olusturma', models.DateTimeField(auto_now_add=True)),
                ('hedef_sube', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='panel.sube')),
            ],
            options={
                'ordering': ['-olusturma'],
            },
        ),
    ]
