# Generated by Django 6.0.7 on 2026-08-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0051_geribildirim_gonderen_kaldir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denetim',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='denetimbolum',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='denetimcevap',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='denetimmadde',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='egitimacikcevap',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mutfakmaliyetkalemi',
            name='fiyat',
            field=models.DecimalField(decimal_places=2, help_text='Kg için ₺/kg, Litre için ₺/litre, Adet için ₺/adet.', max_digits=10, verbose_name='Birim Fiyatı (₺)'),
        ),
        migrations.AlterField(
            model_name='mutfaktarifkalemi',
            name='miktar',
            field=models.DecimalField(decimal_places=1, help_text='Kg için gram, Litre için ml, Adet için tam sayı girin.', max_digits=10, verbose_name='Miktar'),
        ),
        migrations.AlterField(
            model_name='personel',
            name='manuel_giris_yetkisi',
            field=models.BooleanField(default=False, help_text='İşaretliyse: Şef/Mağaza Müdürü rolündeyse kendi şubesindeki personel için, diğer rollerde ise kendi adına, kamera QR olmadan manuel mola/mesai başlatıp bitirebilir.', verbose_name='Manuel Mola/Mesai Girişi Yetkisi'),
        ),
    ]
