# Generated by Django 6.1.1 on 2026-09-19 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0056_academy_favori_kapak'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subestok',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='subestok',
            name='sube',
        ),
        migrations.RemoveField(
            model_name='subestok',
            name='urun',
        ),
        migrations.DeleteModel(
            name='StokHareket',
        ),
        migrations.DeleteModel(
            name='SubeStok',
        ),
    ]
