# -*- coding: utf-8 -*-
"""Kahve kültürü/sektörü günlük soru bankası.
Her kayıt: (kategori, soru, A, B, C, D, dogru) ; dogru: "A"/"B"/"C"/"D".
Yüklemek için: python manage.py soru_yukle
"""

SORULAR = [
    ("Tarih", "Kahvenin anavatanı olarak kabul edilen ülke hangisidir?", "Brezilya", "Yemen", "Etiyopya", "Kolombiya", "C"),
    ("Tarih", "Efsaneye göre kahveyi keçilerinin hareketlenmesiyle keşfeden çoban kimdir?", "Baba Budan", "Kaldi", "Omar", "Sina", "B"),
    ("Tarih", "Kahve ilk olarak hangi içecek biçiminde yaygınlaştığı düşünülür?", "Süzme", "Espresso", "Kaynatılarak", "Soğuk demleme", "C"),
    ("Tarih", "Dünyada en çok kahve üreten ülke hangisidir?", "Vietnam", "Kolombiya", "Brezilya", "Etiyopya", "C"),
    ("Tarih", "Robusta üretiminde dünya lideri olan ülke hangisidir?", "Brezilya", "Vietnam", "Uganda", "Hindistan", "B"),
    ("Tarih", "İlk kahvehaneler tarihsel olarak hangi şehirlerde yaygınlaşmıştır?", "Viyana-Berlin", "Roma-Atina", "İstanbul-Kahire", "Paris-Londra", "C"),
    ("Tarih", "Osmanlı'da kahvenin İstanbul'a gelişi yaklaşık hangi yüzyıldadır?", "18. yüzyıl", "19. yüzyıl", "16. yüzyıl", "14. yüzyıl", "C"),
    ("Tarih", "Kahve kelimesinin kökeni olan Arapça sözcük hangisidir?", "Kava", "Bunn", "Qahwa", "Kaffa", "C"),
    ("Tarih", "'Cappuccino' adının ilham aldığı düşünülen topluluk hangisidir?", "Cizvitler", "Fransiskenler", "Kapusen rahipleri", "Benediktenler", "C"),
    ("Tarih", "Espresso makinesinin geliştiği ve yaygınlaştığı ülke hangisidir?", "ABD", "İtalya", "İspanya", "Fransa", "B"),
    ("Tarih", "Türk kahvesi UNESCO Somut Olmayan Kültürel Miras listesine yaklaşık hangi yılda girmiştir?", "2018", "1995", "2003", "2013", "D"),
    ("Tarih", "Latin Amerika'da kahveyi yaygınlaştıran sömürge gücü ağırlıkla hangisiydi?", "İngiltere", "İspanya ve Portekiz", "Hollanda", "Rusya", "B"),
    ("Tarih", "Kahve çekirdeği aslında bir meyvenin neresidir?", "Kabuğu", "Yaprağı", "Çiçeği", "Çekirdeği (tohumu)", "D"),
    ("Tarih", "Kahve bitkisinin meyvesine ne ad verilir?", "Pod", "Drupe kabuğu", "Berry kovanı", "Cherry (kiraz)", "D"),
    ("Tarih", "'Üçüncü dalga kahve' akımı neyi vurgular?", "Zincir mağazacılık", "Kalite, köken ve şeffaflık", "Hız ve otomasyon", "Ucuzluk", "B"),
    ("Çekirdek", "En yaygın iki kahve türü hangileridir?", "Arabica ve Robusta", "Typica ve Bourbon", "Liberica ve Excelsa", "Geisha ve Catuai", "A"),
    ("Çekirdek", "Genel olarak daha yüksek kafein içeren tür hangisidir?", "Liberica", "İkisi eşit", "Robusta", "Arabica", "C"),
    ("Çekirdek", "Arabica genellikle hangi özelliğiyle bilinir?", "Daha aromatik ve asitli", "Daha sert ve acı", "Kafeini çok yüksek", "Tatsız", "A"),
    ("Çekirdek", "Arabica genellikle hangi rakımlarda daha kaliteli yetişir?", "Yüksek rakım", "Sadece çölde", "Deniz seviyesi", "Kutuplarda", "A"),
    ("Çekirdek", "Robusta bitkisi Arabica'ya göre genellikle nasıldır?", "Daha az verimli", "Daha narin", "Daha pahalı", "Hastalıklara daha dayanıklı", "D"),
    ("Çekirdek", "Bir kahve kirazının içinde tipik olarak kaç çekirdek bulunur?", "2", "6", "4", "1", "A"),
    ("Çekirdek", "Tek çekirdekli, yuvarlak kahve tanesine ne ad verilir?", "Maragogype", "Peaberry", "Mutant", "Caracoli kabuğu", "B"),
    ("Çekirdek", "Aşağıdakilerden hangisi bir Arabica çeşididir?", "Santos", "Excelsa", "Vietnam", "Bourbon", "D"),
    ("Çekirdek", "Çok aranan, çiçeksi ve çay benzeri profiliyle ünlü çeşit hangisidir?", "Catimor", "Maragogype", "Geisha (Gesha)", "Robusta", "C"),
    ("Çekirdek", "Kahve kuşağı (bean belt) hangi bölgeler arasındadır?", "Sadece Asya", "Sadece Avrupa", "Yengeç ve Oğlak dönenceleri arası", "Kutuplar", "C"),
    ("Çekirdek", "Yıkanmış (washed) işleme yönteminin tipik etkisi nedir?", "Daha mayhoş ve fermente", "Daha yağlı", "Daha az aroma", "Daha temiz ve asitli profil", "D"),
    ("Çekirdek", "Natural (kuru) işleme genellikle neye yol açar?", "Daha düz tat", "Daha meyvemsi ve yoğun tatlılık", "Asitliği yok eder", "Kafeini artırır", "B"),
    ("Çekirdek", "Honey process işlemede çekirdek üzerinde ne bir miktar bırakılır?", "Mucilage (yapışkan tatlı tabaka)", "Kabuk tamamen", "Çiçek", "Yaprak", "A"),
    ("Çekirdek", "Kahve çekirdeğindeki uyarıcı temel madde hangisidir?", "Tein", "Kafein", "Kinin", "Taurin", "B"),
    ("Çekirdek", "Decaf (kafeinsiz) kahvede kafein durumu nedir?", "Hiç yoktur, tamamen sıfırdır", "Artırılmıştır", "Değişmez", "Büyük oranda azaltılmıştır", "D"),
    ("Kavurma", "Açık kavrum (light roast) genellikle neyi öne çıkarır?", "Yanık tat", "Asitlik ve köken karakteri", "Yoğun acılık", "Çikolata-karamel", "B"),
    ("Kavurma", "Koyu kavrum (dark roast) tipik olarak neyi artırır?", "Acı/kavrulmuş ve gövdeli notaları", "Çiçeksi aromayı", "Asitliği", "Meyveliliği", "A"),
    ("Kavurma", "Kavurma sırasında duyulan ilk çatlama sesine ne denir?", "Bloom", "Purge", "Drop", "First crack", "D"),
    ("Kavurma", "Kavurma ilerledikçe çekirdeğin rengi nasıl değişir?", "Değişmez", "Koyudan açığa", "Yeşilden maviye", "Açıktan koyuya", "D"),
    ("Kavurma", "Çiğ/işlenmemiş kahve çekirdeğinin rengi nasıldır?", "Kahverengi", "Yeşilimsi", "Kırmızı", "Siyah", "B"),
    ("Kavurma", "Çok koyu kavrumda çekirdek yüzeyinde ne görülebilir?", "Şeker kristali", "Yağ tabakası", "Tuz", "Küf", "B"),
    ("Kavurma", "Espresso için genelde hangi kavrum aralığı yaygındır?", "Sadece çiğ", "Çok açık", "Orta-koyu", "Yeşil", "C"),
    ("Kavurma", "Kavurma sonrası kahvenin CO2 saldığı sürece ne denir?", "Oksitlenme yok", "Bloom kaybı", "Çürüme", "Degassing (gaz çıkışı)", "D"),
    ("Kavurma", "Filtre demlemede çoğu uzman hangi kavrumu tercih eder?", "Açık-orta", "Çok koyu", "Çiğ", "Yanık", "A"),
    ("Demleme", "V60 hangi tür bir demleme yöntemidir?", "Pour over (üzerine dökme/süzme)", "Daldırma", "Basınçlı", "Kaynatma", "A"),
    ("Demleme", "French press hangi yöntem ailesindendir?", "Immersion (daldırma)", "Soğuk damlama", "Espresso", "Pour over", "A"),
    ("Demleme", "AeroPress neyle çalışır?", "Hava basıncı/piston", "Buhar kazanı", "Mıknatıs", "Elektrik", "A"),
    ("Demleme", "Chemex'in ayırt edici özelliği nedir?", "Basınçlı", "Metal filtre", "Kalın kağıt filtre", "Filtresiz", "C"),
    ("Demleme", "Moka pot neyi kullanarak kahveyi yukarı iter?", "Yerçekimi", "Elektrik pompası", "Vakum", "Buhar basıncı", "D"),
    ("Demleme", "Cold brew (soğuk demleme) tipik olarak ne kadar sürede demlenir?", "2 dakika", "30 saniye", "1 hafta", "12-24 saat", "D"),
    ("Demleme", "Türk kahvesi nasıl hazırlanır?", "Cezvede kaynatılarak", "Soğuk demlenerek", "Süzülerek", "Basınçla", "A"),
    ("Demleme", "Türk kahvesinde çekirdek ne kadar öğütülür?", "Orta", "Çok ince (toz)", "İri", "Öğütülmez", "B"),
    ("Demleme", "Espresso çekiminde su yaklaşık kaç bar basınçla geçer?", "1 bar", "30 bar", "9 bar", "0.5 bar", "C"),
    ("Demleme", "Standart tek shot espresso için tipik çekim süresi yaklaşık kaçtır?", "10 dakika", "5 saniye", "25-30 saniye", "2 dakika", "C"),
    ("Demleme", "Pour over'da ilk az su ekleyip beklemeye (gaz çıkışı) ne denir?", "Purge", "Tamping", "Crema", "Bloom", "D"),
    ("Demleme", "French press'te demleme sonrası pistonu ne yaparız?", "Çeviririz", "Hızla yukarı çekeriz", "Hiç dokunmayız", "Yavaşça aşağı bastırırız", "D"),
    ("Demleme", "Genel kural olarak iri öğütme hangi yönteme uygundur?", "Türk kahvesi", "Espresso", "French press", "V60 ince", "C"),
    ("Demleme", "Espresso için öğütme nasıl olmalıdır?", "Toz", "Öğütülmemiş", "Çok iri", "İnce", "D"),
    ("Demleme", "Filtre kahvede yaygın altın oran (kahve:su) yaklaşık nedir?", "1:2", "1:1", "1:50", "~1:15-1:17", "D"),
    ("Demleme", "AeroPress'in tersten (inverted) yöntemi neyi amaçlar?", "Daha hızlı soğutma", "Basıncı 9 bara çıkarmak", "Filtreyi atlamak", "Daha uzun daldırma kontrolü", "D"),
    ("Demleme", "Siphon (vakum) demlemede ısı kaynağı kaldırılınca ne olur?", "Kahve yukarı çıkar", "Patlar", "Vakumla aşağı iner", "Donar", "C"),
    ("Demleme", "Demleme suyu sıcaklığı genelde hangi aralıkta önerilir?", "90-96°C", "20°C", "100°C kaynar", "40-50°C", "A"),
    ("Demleme", "Aşırı ekstraksiyon (over-extraction) tipik olarak neye yol açar?", "Acı ve buruk tat", "Tuzluluk", "Ekşi tat", "Tatsızlık", "A"),
    ("Demleme", "Yetersiz ekstraksiyon (under-extraction) tipik olarak neye yol açar?", "Ekşi/sour ve zayıf tat", "Yanıklık", "Yağlılık", "Acılık", "A"),
    ("Espresso", "Espresso üzerindeki altın-kahverengi köpüğe ne denir?", "Bloom", "Mousse", "Foam", "Crema", "D"),
    ("Espresso", "Cappuccino klasik olarak hangi üç bileşenden oluşur?", "Sadece süt", "Espresso + buharlı süt + süt köpüğü", "Espresso + buz", "Espresso + su + şurup", "B"),
    ("Espresso", "Latte'de süt oranı cappuccino'ya göre nasıldır?", "Daha çok süt", "Eşit", "Süt yok", "Daha az süt", "A"),
    ("Espresso", "Flat white'ı latte'den ayıran tipik özellik nedir?", "Soğuk olması", "Daha çok köpük", "Şuruplu olması", "Daha ince mikroköpük ve daha güçlü kahve oranı", "D"),
    ("Espresso", "Macchiato kelime anlamı olarak ne demektir?", "Soğuk", "Büyük", "Lekelenmiş/işaretlenmiş", "Tatlı", "C"),
    ("Espresso", "Americano nasıl yapılır?", "Süt + şurup", "Çift süt", "Espresso + sıcak su", "Soğuk demleme", "C"),
    ("Espresso", "Cortado tipik olarak neyi içerir?", "Espresso + az miktar buharlı süt", "Sadece su", "Buz + süt", "Bol köpük", "A"),
    ("Espresso", "Süt buharlarken hedeflenen ipeksi dokuya ne denir?", "Tortu", "Kabuk", "Crema", "Mikroköpük (microfoam)", "D"),
    ("Espresso", "Latte art için süt köpüğü nasıl olmalıdır?", "Köpüksüz", "İnce, parlak ve akışkan", "Buz gibi", "İri kabarcıklı ve kuru", "B"),
    ("Espresso", "İnek sütünde köpürmeyi sağlayan temel bileşen ağırlıkla nedir?", "Şeker", "Sadece su", "Yağ ve protein", "Kafein", "C"),
    ("Espresso", "Espresso çekiminde 'channeling' nedir?", "Cremanın kaybı", "Sütün taşması", "Makinenin ısınması", "Suyun puck içinde düzensiz kanallardan akması", "D"),
    ("Espresso", "Portafiltreye kahveyi sıkıştırma işlemine ne denir?", "Dosing", "Tamping", "Pulling", "Purging", "B"),
    ("Espresso", "Tamping'in amacı nedir?", "Suyu eklemek", "Kahveyi ısıtmak", "Köpük yapmak", "Kahveyi eşit yoğunlukta düzleştirmek", "D"),
    ("Espresso", "Doppio ne demektir?", "Çift (double) shot", "Sütlü", "Yarım shot", "Tek shot", "A"),
    ("Espresso", "Ristretto espresso'ya göre nasıldır?", "Daha az su, daha yoğun", "Soğuk", "Daha çok su", "Sütlü", "A"),
    ("Espresso", "Lungo espresso'ya göre nasıldır?", "Köpüklü", "Sütlü", "Daha çok su, daha uzun çekim", "Daha az su", "C"),
    ("Espresso", "Süt köpürtürken buhar borusuna ne denir?", "Portafilter", "Group head", "Steam wand", "Hopper", "C"),
    ("Espresso", "Espresso yapılan grup başlığına İngilizce ne denir?", "Steam wand", "Doser", "Group head", "Hopper", "C"),
    ("Espresso", "Süt köpürtmede önerilen hedef sıcaklık yaklaşık nedir?", "95°C", "100°C", "40°C", "60-65°C", "D"),
    ("Espresso", "Mocha (mocha latte) tipik olarak neyi içerir?", "Limon", "Çikolata + espresso + süt", "Çay", "Sadece su", "B"),
    ("Ekipman", "Kahve öğütücüde tercih edilen bıçak tipi hangisidir?", "Mıknatıs", "Burr (konik/düz değirmen)", "Pervane (blade)", "Testere", "B"),
    ("Ekipman", "Burr öğütücünün pervaneye üstünlüğü nedir?", "Daha ucuz", "Elektriksiz", "Daha eşit öğütme", "Daha gürültülü", "C"),
    ("Ekipman", "Portafilter ne işe yarar?", "Öğütülmüş kahveyi tutup espresso çeker", "Su ısıtır", "Çekirdek kavurur", "Süt köpürtür", "A"),
    ("Ekipman", "Barista terazisi (scale) neden kullanılır?", "Renk ölçümü", "Sıcaklık ölçümü", "Basınç ölçümü", "Doz ve verim ölçümü", "D"),
    ("Ekipman", "Espresso makinesinde su sıcaklığını dengeleyen sisteme örnek nedir?", "GPS", "Bluetooth", "PID kontrol", "RFID", "C"),
    ("Ekipman", "Çekirdek haznesine (öğütücü üstü) ne denir?", "Wand", "Group", "Puck", "Hopper", "D"),
    ("Ekipman", "Espresso sonrası portafilterde kalan ıslak kahve keki neye benzetilir?", "Puck", "Foam", "Bloom", "Crema", "A"),
    ("Ekipman", "Distribütör/WDT aracı ne için kullanılır?", "Öğütülmüş kahveyi eşit dağıtmak", "Tartmak", "Süt köpürtmek", "Su ısıtmak", "A"),
    ("Ekipman", "Gooseneck (kuğu boyunlu) ibrik ne için idealdir?", "Espresso çekme", "Pour over'da kontrollü su dökme", "Kavurma", "Süt buharlama", "B"),
    ("Ekipman", "Refraktometre kahvede neyi ölçer?", "Sıcaklık", "Basınç", "TDS / ekstraksiyon oranı", "Ağırlık", "C"),
    ("Duyusal", "Profesyonel kahve tadımına ne ad verilir?", "Tasting menu", "Brewing", "Roasting", "Cupping", "D"),
    ("Duyusal", "Kahvede 'body' (gövde) neyi ifade eder?", "Ağızdaki doku/ağırlık hissi", "Sesini", "Sıcaklığı", "Rengi", "A"),
    ("Duyusal", "Kahvede 'acidity/asitlik' olumlu anlamda neyi ifade eder?", "Tuzluluk", "Acılık", "Canlı, parlak tat", "Bozulma", "C"),
    ("Duyusal", "Cupping'de kahveyi yüksek sesle höpürdetmenin amacı nedir?", "Soğutmak", "Aromayı tüm damağa yaymak", "Köpük yapmak", "Gösteriş", "B"),
    ("Duyusal", "'Aftertaste' (bitiş) neyi ifade eder?", "Yutduktan sonra kalan tat", "İlk koku", "Renk", "Sıcaklık", "A"),
    ("Duyusal", "SCA puanlamasında 80+ alan kahveler nasıl sınıflanır?", "Specialty (nitelikli)", "Çöp", "Robusta", "Decaf", "A"),
    ("Duyusal", "Kahvede çiçeksi/meyvemsi notalar daha çok hangi profilde belirgindir?", "Çok koyu kavrum", "Açık kavrum", "Yanık", "Kafeinsiz", "B"),
    ("Saklama", "Kavrulmuş kahve en iyi nasıl saklanır?", "Güneşte açıkta", "Buzlukta nemli", "Serin, kuru, ışıksız ve hava almayan kapta", "Açık torbada", "C"),
    ("Saklama", "Kahvenin tazeliği için en iyi uygulama hangisidir?", "Islak saklamak", "Demlemeden hemen önce öğütmek", "Güneşte tutmak", "Aylarca öğütülmüş bekletmek", "B"),
    ("Saklama", "Öğütülmüş kahve neden çabuk bayatlar?", "Donar", "Su emmez", "Kafein artar", "Yüzey alanı artar, oksitlenir", "D"),
    ("Saklama", "Kahveyi saklarken en büyük düşmanlardan biri nedir?", "Vakum", "Karanlık", "Oksijen/nem/ışık/ısı", "Soğuk kuru hava", "C"),
    ("Saklama", "Kavrulmuş kahve genelde ne zaman en iyi içilir?", "Kavrumdan hemen sonra", "1 yıl sonra", "Hiç beklemeden çiğ", "Birkaç günlük dinlenme sonrası, birkaç hafta içinde", "D"),
    ("Sektör", "Bir kafede 'barista' kimdir?", "Garson şefi", "Kasiyer", "Muhasebeci", "Kahve hazırlayan uzman", "D"),
    ("Sektör", "'Specialty coffee' kavramı neyi vurgular?", "Ucuzluk", "Hız", "Yüksek kalite ve izlenebilirlik", "Çok şeker", "C"),
    ("Sektör", "Adil ticaret (Fair Trade) sertifikası neyi hedefler?", "Daha çok kafein", "Daha koyu kavrum", "Hızlı servis", "Üreticiye adil bedel", "D"),
    ("Sektör", "Müşteriye kahve servisinde önce ne yapılması beklenir?", "Karıştırmamak", "Yüksek sesle bağırmak", "Bekletmek", "Hijyen ve temiz ekipman", "D"),
    ("Sektör", "Süt köpürtmeden önce ve sonra buhar borusunu ne yapmak gerekir?", "Kırmak", "Boyamak", "Temizlemek/purge etmek", "Buzlamak", "C"),
    ("Sektör", "Bir kahve dükkanında çapraz bulaşmayı önlemek için en önemli şey nedir?", "Hızlı müzik", "Karanlık ortam", "Yüksek fiyat", "Hijyen kuralları", "D"),
    ("Sektör", "Latte art yarışmalarında en bilinen iki temel figür hangisidir?", "Spiral ve nokta", "Kare ve üçgen", "Kalp ve Rozet (rosetta)", "Yıldız ve ay", "C"),
    ("Sektör", "Barista için 'dialing in' ne demektir?", "Öğütme/doz/süreyi ideal tada ayarlamak", "Süt sipariş etmek", "Makineyi kapatmak", "Telefonla sipariş", "A"),
    ("Sektör", "Bir kafede FIFO ilkesi neyi ifade eder?", "İndirim", "Hızlı servis", "Çok satış", "İlk giren ilk çıkar (stok tazeliği)", "D"),
    ("Sektör", "Kahve servisinde 'to-go' ne demektir?", "Burada içme", "İkram", "İade", "Paket/dışarı götürme", "D"),
    ("Kültür", "İtalya'da sabah dışında genelde 'ayıplanan' içecek hangisidir?", "Espresso", "Çay", "Cappuccino (öğleden sonra)", "Su", "C"),
    ("Kültür", "'Espresso' İtalyanca olarak neyi çağrıştırır?", "Hızlı/sıkıştırılmış (express)", "Soğuk", "Yavaş", "Tatlı", "A"),
    ("Kültür", "İrlanda kahvesi (Irish coffee) neyi içerir?", "Kahve + limon", "Kahve + viski + krema", "Sadece süt", "Kahve + çay", "B"),
    ("Kültür", "Viyana kahvesi tipik olarak neyle servis edilir?", "Çırpılmış krema", "Tuz", "Limon", "Buz", "A"),
    ("Kültür", "Yunan/Frappe kahvesi nasıldır?", "Kaynatılmış", "Sütsüz sıcak", "Soğuk, çalkalanmış köpüklü kahve", "Sıcak espresso", "C"),
    ("Kültür", "Vietnam kahvesinde geleneksel olarak ne kullanılır?", "Limon", "Tuz", "Bal", "Yoğunlaştırılmış (kondanse) süt", "D"),
    ("Kültür", "İspanya'da 'café con leche' ne demektir?", "Sade espresso", "Buzlu kahve", "Çay", "Sütlü kahve", "D"),
    ("Kültür", "Portekiz'de küçük espresso'ya ne ad verilir?", "Cortado", "Latte", "Bica", "Mocha", "C"),
    ("Kültür", "Avustralya/Yeni Zelanda'nın popülerleştirdiği içecek hangisidir?", "Flat white", "Frappe", "Mocha", "Americano", "A"),
    ("Kültür", "'Affogato' nasıl bir tatlıdır?", "Kek üzerine süt", "Buz üzerine çay", "Çikolata sos", "Dondurma üzerine espresso", "D"),
    ("Kültür", "Türk kahvesi yanında geleneksel olarak ne ikram edilir?", "Tuz", "Çay", "Su (ve lokum)", "Limon", "C"),
    ("Kültür", "Türk kahvesinde 'köpük' neden önemlidir?", "Renk", "Kafein", "Tatlandırıcı", "Sunum ve kalite göstergesi", "D"),
    ("Kültür", "Fal geleneği hangi kahveyle ilişkilendirilir?", "Espresso", "Cold brew", "Filtre", "Türk kahvesi", "D"),
    ("Kültür", "'Kaymaklı/sütlü' yerine 'sade' Türk kahvesi ne demektir?", "Sütlü", "Köpüksüz", "Soğuk", "Şekersiz", "D"),
    ("Kültür", "Türk kahvesinde 'orta' ne anlama gelir?", "Orta öğütme", "Orta şekerli", "Orta fincan", "Orta sıcaklık", "B"),
    ("Demleme", "Tipik bir cezve Türk kahvesinde fincan başına yaklaşık ne kadar kahve konur?", "5 yemek kaşığı", "1-2 tatlı kaşığı", "Hiç", "Yarım fincan", "B"),
    ("Demleme", "French press için önerilen öğütme nasıldır?", "İri/kaba", "İnce toz", "Espresso inceliği", "Öğütülmemiş", "A"),
    ("Demleme", "Cold brew genelde nasıl içilir?", "Kaynatılarak", "Konsantre olarak seyreltilip soğuk", "Buharla", "Sıcak", "B"),
    ("Demleme", "Espresso'da doz (gram kahve) genelde hangi aralıktadır?", "100 g", "1-2 g", "7-10 g (tek), 16-20 g (çift)", "50 g", "C"),
    ("Demleme", "Pour over'da toplam demleme süresi yaklaşık ne kadardır?", "2.5-4 dakika", "5 saniye", "30 dakika", "1 saniye", "A"),
    ("Demleme", "Demlemede kullanılan su kalitesi neden önemlidir?", "Tadın çoğu sudur", "Sadece sıcaklık", "Önemsizdir", "Renk için", "A"),
    ("Demleme", "Çok sert (kireçli) su demlemede neye yol açabilir?", "Daha çok köpük", "Kafein artışı", "Daha iyi tat", "Makinede kireç ve bozuk ekstraksiyon", "D"),
    ("Demleme", "Espresso 'puck'ı çok hızlı akıyorsa ne yapılır?", "Daha iri öğütülür", "Daha ince öğütülür", "Su artırılır", "Isı düşürülür", "B"),
    ("Demleme", "Espresso çok yavaş/damla damla akıyorsa ne yapılır?", "Daha iri öğütülür", "Daha ince öğütülür", "Doz artırılır", "Beklenir", "A"),
    ("Demleme", "Moka pot'ta kahve genelde nasıl içilir?", "Yoğun, espresso benzeri", "Soğuk", "Köpüklü latte", "Çok sulu", "A"),
    ("Espresso", "Bir 'shot' espresso tipik hacmi yaklaşık nedir?", "5 ml", "200 ml", "500 ml", "25-30 ml", "D"),
    ("Espresso", "Crema'nın iyi olması neyi gösterebilir?", "Taze çekirdek ve iyi çekim", "Bayatlık", "Süt", "Su fazlalığı", "A"),
    ("Espresso", "Latte'de tipik espresso:süt oranı yaklaşık nedir?", "1:1", "10:1", "Sütsüz", "yaklaşık 1:3-1:5", "D"),
    ("Espresso", "Cappuccino genelde hangi fincan boyutunda servis edilir?", "Küçük-orta (~150-180 ml)", "Shot bardağı", "1 litre", "Kova", "A"),
    ("Espresso", "Süt köpürtürken 'çığlık' sesi neyi gösterir genelde?", "Makinenin hazır olduğunu", "Sütün bittiğini", "Yanlış pozisyon/aşırı hava", "Doğru teknik", "C"),
    ("Espresso", "Buharlanan süt için en uygun süt sıcaklık sınırı yaklaşık nedir?", "65°C civarı (yakmadan)", "0°C", "30°C", "100°C üstü", "A"),
    ("Espresso", "Latte art dökmeden önce süt ne yapılmalı?", "Kaynamalı", "Donmalı", "Bekletilmeli ayrışsın", "Hafifçe çevrilip parlatılmalı (swirl)", "D"),
    ("Espresso", "Bitkisel sütlerde köpürmeyi etkileyen ana faktör nedir?", "Sıcaklık yok", "Protein/yağ içeriği ve barista formülü", "Renk", "Marka logosu", "B"),
    ("Espresso", "Espresso'da 'blonde/sarı' akış sonu neyi gösterir?", "Su bittiğini", "Başladığını", "Ekstraksiyon sonuna gelindiğini", "Süt eklendiğini", "C"),
    ("Espresso", "Çift espresso bazlı içecekte kahve karakteri neden daha belirgindir?", "Daha çok su", "Daha çok kahve dozu", "Daha çok şeker", "Soğuk olduğu için", "B"),
    ("Tarih", "Kahvenin Avrupa'ya yayılmasında köprü olan imparatorluk hangisidir?", "Rus", "Osmanlı", "Roma", "İnka", "B"),
    ("Tarih", "Etiyopya'da kahvenin bulunduğu söylenen bölgenin adı kahveye ilham vermiş olabilir; bu bölge nedir?", "Sidamo köyü", "Yirgacheffe köprüsü", "Kaffa", "Harar limanı", "C"),
    ("Tarih", "Yemen'in kahve ticaretinde ünlü liman şehri hangisiydi?", "Aden kalesi", "Sana'a", "Mokka (Mocha)", "Taiz", "C"),
    ("Tarih", "'Mocha' kelimesinin kahveyle ilişkisi nereden gelir?", "Fransa'dan", "İtalya'dan", "Çikolatadan", "Yemen'deki Mokka limanından", "D"),
    ("Tarih", "Brezilya kahve üretiminde dünyada kaçıncı sıradadır?", "Sonuncu", "Onuncu", "Birinci", "Yirminci", "C"),
    ("Tarih", "Kolombiya kahvesi genelde neyiyle bilinir?", "Kafeinsizlik", "Acılık", "Sadece Robusta", "Dengeli, yumuşak Arabica", "D"),
    ("Tarih", "Etiyopya kahveleri sıklıkla hangi profille anılır?", "Yanık", "Tuzlu", "Tatsız", "Çiçeksi ve meyvemsi", "D"),
    ("Tarih", "Kahve ağacının çiçekleri neye benzer ve nasıl kokar?", "Kırmızı, kokusuz", "Mavi, naneli", "Sarı, limonlu", "Beyaz, yasemin benzeri", "D"),
    ("Tarih", "Bir kahve ağacının ekonomik verime ulaşması yaklaşık kaç yıl alır?", "Hemen", "3-4 yıl", "1 ay", "20 yıl", "B"),
    ("Tarih", "Dünyada kahve hasadı genelde neye göre yapılır?", "Yağmurla", "Her gün", "Olgunluk/mevsim (kiraz kızarınca)", "Rastgele", "C"),
    ("Çekirdek", "Selektif hasat (selective picking) nedir?", "Makineyle hepsini", "Tüm dalı sıyırmak", "Yere düşeni toplamak", "Sadece olgun kirazları toplamak", "D"),
    ("Çekirdek", "Kahve çekirdeğindeki 'parchment' nedir?", "Kök", "Çekirdeği saran ince kabuk", "Yaprak", "Çiçek", "B"),
    ("Çekirdek", "'Single origin' ne demektir?", "Tek kaynak/menşe", "Tek kavurma", "Tek kişilik", "Tek shot", "A"),
    ("Çekirdek", "'Blend' ne demektir?", "Harman (birden çok çekirdeğin karışımı)", "Tek köken", "Öğütülmüş", "Kavrulmamış", "A"),
    ("Çekirdek", "Robusta espresso harmanlarına neden eklenir?", "Daha az kafein", "Ucuz olduğu için asla", "Daha çok crema ve gövde", "Çiçeksi tat", "C"),
    ("Çekirdek", "Yüksek rakım kahve kalitesini genelde nasıl etkiler?", "Daha yoğun, kompleks tat", "Kafeini sıfırlar", "Tadı bozar", "Etkisiz", "A"),
    ("Çekirdek", "'Defect/kusurlu çekirdek' ayıklaması neden yapılır?", "Tat kalitesini korumak", "Gereksizdir", "Renk için", "Ağırlık için", "A"),
    ("Çekirdek", "Yeşil (çiğ) kahve raf ömrü kavrulmuşa göre nasıldır?", "Sınırsız değil ama çok kısa", "Daha kısa", "Aynı", "Daha uzun", "D"),
    ("Ekipman", "Espresso makinesinde grup başlığının periyodik temizliğine ne denir?", "Tamping", "Cupping", "Bloom", "Backflush", "D"),
    ("Ekipman", "Backflush için kullanılan kör filtreye ne denir?", "Puck", "Wand", "Hopper", "Blind filter", "D"),
    ("Ekipman", "Öğütücü ayarı (grind setting) neyi değiştirir?", "Süt yağını", "Su sıcaklığını", "Öğütme inceliğini", "Renk", "C"),
    ("Ekipman", "Espresso tabletini düzleştiren araca ne denir?", "Pense", "Kepçe", "Tamper", "Spatula", "C"),
    ("Ekipman", "Süt sürahisinin (pitcher) ucu neden sivridir?", "Süs", "Ağırlık", "Isı", "Latte art akışı için", "D"),
    ("Ekipman", "Kahve makinesinde kireç çözme işlemine ne denir?", "Purging", "Descaling", "Tamping", "Backflush", "B"),
    ("Ekipman", "Dozajlamada 'single dosing' ne demektir?", "Su dozu", "Süt dozu", "Her çekim için ayrı tartılan çekirdek", "Sürekli hazne", "C"),
    ("Ekipman", "Espresso makinesinde 'boiler' ne işe yarar?", "Köpük süsleme", "Öğütme", "Su ısıtma/buhar üretimi", "Tartma", "C"),
    ("Duyusal", "Kahvede 'balance/denge' neyi ifade eder?", "Sadece acılık", "Sadece tatlılık", "Tatların uyumu", "Renk", "C"),
    ("Duyusal", "'Clean cup' (temiz fincan) ne demektir?", "Soğuk", "Bardağın yıkanmış olması", "Kusursuz, yabancı tat olmayan", "Sütlü", "C"),
    ("Duyusal", "Espresso'da aşırı acılık çoğunlukla neyi işaret eder?", "Az kahve", "Aşırı ekstraksiyon/çok ince öğütme", "Soğuk su", "Süt fazlası", "B"),
    ("Duyusal", "Espresso'da ekşilik/sourluk çoğunlukla neyi işaret eder?", "Aşırı süt", "Yetersiz ekstraksiyon/çok iri öğütme", "Fazla bekleme", "Çok ince öğütme", "B"),
    ("Duyusal", "SCA flavor wheel (aroma tekerleği) ne için kullanılır?", "Tat/aromaları tanımlamak", "Kavurma", "Fiyatlama", "Tartım", "A"),
    ("Duyusal", "Kahvede 'sweetness/tatlılık' kaynağı çoğunlukla nedir?", "Süt", "Eklenen şeker zorunlu", "Tuz", "Doğal şekerler ve iyi ekstraksiyon", "D"),
    ("Genel", "Bir fincan filtre kahvede kafein robustaya kıyasla arabica'da nasıldır?", "Sıfır", "Eşit", "Genelde daha az", "Her zaman daha çok", "C"),
    ("Genel", "Kafein vücutta temel olarak ne etkisi yapar?", "Uyku getirir", "Kan şekerini sıfırlar", "Uyanıklık/uyarıcı", "Acıktırır", "C"),
    ("Genel", "Aşırı kafein tüketimi neye yol açabilir?", "Çarpıntı/uykusuzluk", "Hiçbir şey", "Susuzluk hissi yok", "Daha iyi uyku", "A"),
    ("Genel", "Espresso'da fincan başına toplam kafein, filtre kahveye göre genelde nasıldır?", "Hacim küçük olduğu için porsiyonda daha az olabilir", "Her zaman çok daha fazla", "Ölçülemez", "Sıfır", "A"),
    ("Genel", "Kahvenin büyük kısmı neyden oluşur?", "Yağ", "Su", "Şeker", "Tuz", "B"),
    ("Sektör", "Servis sıcaklığı çok yüksek kahve neye yol açar?", "Tat algısını ve müşteri memnuniyetini düşürür", "Daha çok köpük", "Kafein artışı", "Daha iyi tat", "A"),
    ("Sektör", "Süt köpüğü için en hijyenik uygulama nedir?", "Her kullanımdan sonra bezle silip purge etmek", "Hiç temizlememek", "Boyamak", "Suda bekletmek", "A"),
    ("Sektör", "Açılan süt en doğru nerede saklanır?", "Tezgah üstünde", "Soğuk dolapta (buzdolabı)", "Sıcakta", "Camda", "B"),
    ("Sektör", "Bir kafede alerjen bilgisi neden önemlidir?", "Süs", "Renk", "Fiyat", "Müşteri güvenliği (süt/fındık vb.)", "D"),
    ("Sektör", "'Mise en place' kahvede ne demektir?", "İndirim", "Sipariş iptali", "Her şeyi hazır ve düzenli tutmak", "Kapanış", "C"),
    ("Sektör", "Yoğun saatte tutarlı kalite için en kritik şey nedir?", "Müzik", "Şans", "Hız uğruna kaliteden ödün", "Standart reçete ve disiplin", "D"),
    ("Sektör", "Müşteri kahvesini iade ederse ilk yapılması gereken nedir?", "Nazikçe dinleyip yeniden yapmak", "Tartışmak", "Görmezden gelmek", "Ek ücret", "A"),
    ("Sektör", "Kahve ekipmanının günlük bakımının amacı nedir?", "Gürültü", "Elektrik tasarrufu", "Tat tutarlılığı ve hijyen", "Sadece görünüm", "C"),
    ("Sektör", "Çekirdek stok rotasyonunda hangi ilke uygulanır?", "Önce eskiyi kullan (FIFO)", "Hiç kullanma", "Önce yeniyi kullan", "Rastgele", "A"),
    ("Sektör", "Barista 'reçeteyi (recipe)' takip etmezse en olası sonuç nedir?", "Daha hızlı her zaman", "Daha ucuz", "Tutarsız tat", "Daha iyi tat", "C"),
    ("Espresso", "Rosetta (yaprak) figürü nasıl elde edilir?", "Süt sürahisini sallayarak ve ileri çekerek", "Kaşıkla", "Çikolatayla", "Buzla", "A"),
    ("Espresso", "Latte art'ın oluşması için neye ihtiyaç vardır?", "Bol şeker", "Soğuk süt", "İyi crema + ipeksi mikroköpük", "Köpüksüz süt", "C"),
    ("Espresso", "'Free pour' latte art ne demektir?", "Spreyle", "Kalıp/araç olmadan dökerek çizmek", "Kalıpla", "Boyayla", "B"),
    ("Espresso", "'Etching' latte art ne demektir?", "Buharlama", "Öğütme", "Serbest dökme", "Çubukla desen çizmek", "D"),
    ("Genel", "'Barista' kelimesi hangi dilden gelir?", "Japonca", "İtalyanca", "Rusça", "Almanca", "B"),
    ("Genel", "'Crema' rengi ne renge yakındır?", "Yeşil", "Mavi", "Beyaz", "Altın/kahverengi", "D"),
    ("Genel", "Dünya Barista Şampiyonası'nı düzenleyen oluşum kısaltması nedir?", "WHO", "FIFA", "SCA/WCE", "NASA", "C"),
    ("Genel", "'TDS' kahvede neyin kısaltmasıdır?", "Toplam Çözünmüş Katı", "Sıcaklık", "Tat Derecesi", "Toplam Süt", "A"),
    ("Genel", "Espresso İtalya'da genelde nasıl içilir?", "Ayakta, hızlı, az şekerle", "Buzlu", "Litrelik", "Bol sütle", "A"),
    ("Genel", "Kahve telvesi (atık) için sürdürülebilir kullanım örneği nedir?", "Yakıt değil hiçbir şey", "Sadece çöp", "Gübre/peeling", "İçmek", "C"),
    ("Genel", "'Decaf' kahve neden tercih edilir?", "Daha ucuz", "Daha çok kafein", "Daha koyu renk", "Kafeini azaltmak isteyenler için", "D"),
    ("Genel", "Kahvede en taze sonuç için altın kural nedir?", "Taze kavur, taze öğüt, taze demle", "Bekleterek kullan", "Islak sakla", "Çok önce öğüt", "A"),
    ("Genel", "Espresso bazlı içeceklerde tutarlılık için terazi kullanımı neyi sağlar?", "Tekrarlanabilir doz/verim", "Sıcaklık", "Köpük", "Renk", "A"),
    ("Genel", "Kahve dünyasında 'origin' ziyaretleri neyi amaçlar?", "Üreticiyle ilişki ve kalite/şeffaflık", "Reklam", "Tatil", "Hiçbir şey", "A"),
    ("Demleme", "Chemex'in kalın filtresi tada nasıl etki eder?", "Daha berrak, temiz fincan", "Daha yağlı", "Tortulu", "Daha bulanık", "A"),
    ("Demleme", "French press kahvesinde fincanda neden tortu/yağ olur?", "Kağıt filtre", "Soğukluk", "Basınç", "Metal filtre yağ ve ince partikülü geçirir", "D"),
    ("Demleme", "V60'ta merkezden dışa dairesel dökmenin amacı nedir?", "Köpük", "Eşit ıslanma/ekstraksiyon", "Hız", "Süs", "B"),
    ("Demleme", "Türk kahvesinde köpüğü korumak için ne yapılır?", "Buz eklemek", "Kaynatmamak", "Hızlı kaynatıp köpüğü fincanlara paylaştırmak", "Çok karıştırmak", "C"),
    ("Demleme", "Espresso 'puck'ı ıslak ve çamur gibiyse olası sebep nedir?", "Doz/öğütme dengesizliği", "Mükemmel çekim", "Süt fazlası", "Su yokluğu", "A"),
    ("Demleme", "Soğuk demlemede neden daha az acılık/asitlik olur?", "Düşük sıcaklık farklı bileşenleri çözer", "Daha çok kafein", "Tuz eklenir", "Kaynatılır", "A"),
    ("Demleme", "AeroPress'te basınç nasıl uygulanır?", "Elektrikle", "Elle pistonu iterek", "Buharla", "Yerçekimiyle", "B"),
    ("Demleme", "Pour over'da çok yavaş akış neyi gösterebilir?", "Çok ince öğütme/tıkanma", "Çok iri öğütme", "Soğuk su", "Az kahve", "A"),
    ("Demleme", "Batch brew (filtre kahve makinesi) ne için idealdir?", "Yoğun serviste çok bardak", "Kavurma", "Tek shot espresso", "Süt köpürtme", "A"),
    ("Demleme", "Espresso bazlı içecekte taze çekilmiş kahve neden şart?", "Ağırlık için", "Renk için", "Gereksiz", "Aroma ve crema hızla kaybolur", "D"),
    ("Espresso", "Cappuccino'da köpük tabakası latte'ye göre nasıldır?", "İncecik", "Sıvı", "Yok", "Daha kalın/belirgin", "D"),
    ("Espresso", "Flat white tipik hacmi yaklaşık nedir?", "30 ml", "~150-160 ml", "1 litre", "500 ml", "B"),
    ("Espresso", "Espresso servis edilirken tipik olarak ne sunulur?", "Tuz", "Limon", "Buz", "Yanında su", "D"),
    ("Espresso", "Süt köpüğünde büyük baloncuklar oluşursa ne yapılır?", "Atmak zorunlu", "Sürahiyi tıklatıp çevirerek parlatmak", "Kaynatmak", "Buzlamak", "B"),
    ("Espresso", "İyi bir espresso akışı görsel olarak neye benzer?", "Köpük seli", "Damla yok", "Sıcak bal/fare kuyruğu gibi ince akış", "Fışkıran su", "C"),
    ("Espresso", "Espresso bittikten sonra crema zamanla ne olur?", "Dağılır/kaybolur", "Kalınlaşır", "Renk değiştirmez", "Donar", "A"),
    ("Espresso", "Latte makinesinde 'auto-steam' ne sağlar?", "Kavurur", "Tartar", "Sütü belirlenen sıcaklık/dokuya getirir", "Öğütür", "C"),
    ("Espresso", "Çift duvarlı (double wall) fincanın amacı nedir?", "Ağırlık", "Renk", "Süs", "Isıyı korumak/eli yakmamak", "D"),
    ("Çekirdek", "Kahve kirazının olgunlaştığında tipik rengi nedir?", "Kırmızı (bazı çeşitlerde sarı)", "Siyah", "Yeşil", "Mavi", "A"),
    ("Çekirdek", "'Washed' kahvede çekirdek nasıl ayrılır?", "Öğütülerek", "Kavrularak", "Güneşte kuruyarak bütün", "Suyla yıkanıp fermente edilerek", "D"),
    ("Çekirdek", "Robusta'nın espresso harmanındaki katkısı genelde nedir?", "Asitlik", "Çiçeksi aroma", "Tatlılık", "Kalıcı crema ve gövde", "D"),
    ("Çekirdek", "'Microlot' ne demektir?", "Büyük endüstriyel parti", "Kavrulmuş öğütülmüş", "Kafeinsiz", "Küçük, özel ve izlenebilir parti", "D"),
    ("Çekirdek", "Arabica'nın dünya üretimindeki payı kabaca nedir?", "Yaklaşık yarıdan fazlası", "Yüzde 5", "Sıfır", "Tamamı", "A"),
    ("Çekirdek", "Kahvenin botanik olarak ait olduğu bitki cinsi nedir?", "Camellia", "Coffea", "Citrus", "Theobroma", "B"),
    ("Tarih", "İlk kahvehanelere Osmanlı'da ne ad verilirdi?", "Kıraathane/kahvehane", "Han", "Lokanta", "Çayhane", "A"),
    ("Tarih", "Kahve Avrupa'da başta hangi sıfatla anıldı?", "Süt", "Çay", "Zehir kesinlikle", "'Şarabın alternatifi/uyanık içecek'", "D"),
    ("Tarih", "Specialty coffee terimini popülerleştiren isimlerden biri kimdir?", "Omar", "Erna Knutsen", "Napolyon", "Kaldi", "B"),
    ("Tarih", "Dünyada en pahalı kahvelerden biri olan, hayvan sindirimiyle ünlü kahve nedir?", "Kopi Luwak", "Geisha mutlaka", "Mocha", "Robusta", "A"),
    ("Tarih", "Kahve borsasında işlem gören iki ana tür hangileridir?", "Süt ve şeker", "Buğday ve mısır", "Çay ve kakao", "Arabica ve Robusta", "D"),
    ("Kavurma", "'City roast' hangi kavrum seviyesine yakındır?", "Orta", "Çok açık", "Çiğ", "Çok koyu", "A"),
    ("Kavurma", "'French roast' nasıl bir kavrumdur?", "Çok koyu", "Orta", "Çok açık", "Yeşil", "A"),
    ("Kavurma", "İkinci çatlama (second crack) neyi gösterir?", "Sütün hazır olduğunu", "Demlemenin bittiğini", "Koyu kavruma yaklaşıldığını", "Soğumayı", "C"),
    ("Kavurma", "Kavurma profili neyi etkiler?", "Asitlik, tatlılık, gövde dengesini", "Sadece rengi", "Hiçbir şeyi", "Sadece ağırlığı", "A"),
    ("Kavurma", "Aşırı koyu kavrum köken karakterine ne yapar?", "Belirginleştirir", "Büyük ölçüde bastırır", "Asitliği artırır", "Etkisiz", "B"),
    ("Saklama", "Kahve torbalarındaki tek yönlü valf ne işe yarar?", "Koku katmak", "Süs", "CO2'yi dışarı verip oksijeni içeri almamak", "Ağırlık", "C"),
    ("Saklama", "Öğütülmüş kahve ideal olarak ne kadar sürede tüketilmeli?", "Yıllar sonra", "Kısa sürede (tazeyken)", "Önemli değil", "Aylarca sonra", "B"),
    ("Saklama", "Kahveyi buzdolabında açık tutmak neden sorunludur?", "Nem ve koku emer", "Kafein artar", "Daha tazeler", "Renk açılır", "A"),
    ("Duyusal", "Espresso tadımında ilk değerlendirilenlerden biri nedir?", "Aroma/koku", "Fiyatı", "Fincan rengi", "Ağırlığı gram", "A"),
    ("Duyusal", "'Mouthfeel' neyi tanımlar?", "Ağızdaki doku hissi", "Rengi", "Sesi", "Kokuyu", "A"),
    ("Duyusal", "İyi dengelenmiş kahvede asitlik nasıl olmalı?", "Hoş ve canlı, rahatsız etmeyen", "Hiç olmamalı", "Tuzlu", "Sirke gibi keskin", "A"),
    ("Duyusal", "Kahvenin soğudukça tat algısı nasıl değişebilir?", "Asitlik/tatlılık daha belirginleşebilir", "Tamamen kaybolur", "Tuzlanır", "Hiç değişmez", "A"),
    ("Ekipman", "Espresso makinesinde manometre neyi gösterir?", "Zaman yok", "Basınç", "Ağırlık", "Renk", "B"),
    ("Ekipman", "Öğütücüde 'retention' (tutma) sorunu nedir?", "Hazne içinde kahve kalması", "Su kalması", "Süt kalması", "Isı kalması", "A"),
    ("Ekipman", "Bir kafede yedek portafilter neden faydalıdır?", "Ağırlık", "Yoğun serviste hız ve süreklilik", "Süs", "Renk", "B"),
    ("Ekipman", "Tamper çapı ne ile uyumlu olmalı?", "Fincan", "Su tankı", "Portafilter sepeti çapı", "Kaşık", "C"),
    ("Sektör", "Kahve dükkanında 'açılış checklist'i neyi sağlar?", "Sadece süs", "Geç açılış", "İndirim", "Tutarlı ve hijyenik başlangıç", "D"),
    ("Sektör", "Espresso makinesi 'flush' (grup başını akıtma) neden yapılır?", "Su israfı için", "Süt için", "Renk", "Sıcaklık dengesi ve temizlik", "D"),
    ("Sektör", "Müşteriye süt alternatifi sunmak neden önemlidir?", "Sadece moda", "Laktoz/diyet/etik tercihler", "Renk", "Fiyat", "B"),
    ("Sektör", "Tezgah hijyeninde bezlerin ayrılması neden önemli?", "Çapraz bulaşmayı önlemek", "Hız", "Renk uyumu", "Süs", "A"),
    ("Sektör", "Kahve atığını (telve) tezgahta biriktirmek yerine ne yapılır?", "Knock box'a boşaltmak", "Saklamak", "Yere atmak", "Lavaboya tıkamak", "A"),
    ("Sektör", "Yoğun saatte sipariş sırasını yönetmek için en iyi yaklaşım nedir?", "Beklemek", "Rastgele", "Düzenli sıra ve iletişim", "Bağırmak", "C"),
    ("Sektör", "Bir baristanın damak hafızası neden gelişmeli?", "Sadece yarışma", "Gereksiz", "Hız için değil", "Tutarlı kalite kontrolü için", "D"),
    ("Kültür", "'Espresso macchiato' neyle işaretlenir?", "Çikolata", "Tuz", "Az süt köpüğü", "Limon", "C"),
    ("Kültür", "'Latte macchiato'da sıralama nasıldır?", "Sadece süt", "Sadece espresso", "Su + buz", "Süt üzerine espresso eklenir", "D"),
    ("Kültür", "'Ristretto' tat olarak nasıldır?", "Acısız", "Sütlü", "Sulu", "Daha yoğun ve tatlımsı", "D"),
    ("Kültür", "Türk kahvesi pişiminde ateş nasıl olmalı?", "Ateşsiz", "Çok yüksek hızlı", "Buzlu", "Kısık/orta, yavaş", "D"),
    ("Kültür", "Geleneksel Türk kahvesi hangi kapta pişirilir?", "Cezve", "Moka pot", "French press", "Chemex", "A"),
    ("Genel", "Kahvede 'extraction yield' yüzdesi neyi ölçer?", "Çekirdekten çözünen oranı", "Renk", "Süt oranı", "Sıcaklık", "A"),
    ("Genel", "Tipik hedef ekstraksiyon verimi aralığı yaklaşık nedir?", "%50-60", "%90", "%0-2", "%18-22", "D"),
    ("Genel", "Kahvede 'strength/yoğunluk' çoğunlukla neyle ilişkilidir?", "TDS (çözünmüş katı oranı)", "Fiyat", "Bardak boyu", "Renk", "A"),
    ("Genel", "Aynı çekirdekle daha güçlü kahve için ne yapılır?", "Kahve:su oranını artırmak", "Su eklemek", "Bekletmek", "Soğutmak", "A"),
    ("Genel", "Espresso bazlı içeceklerde temel baz nedir?", "Soda", "Çay", "Espresso", "Limonata", "C"),
    ("Genel", "Kahvede sürdürülebilirlik neyi içerir?", "Sadece hız", "Sadece fiyat", "Sadece renk", "Çevre, üretici refahı, izlenebilirlik", "D"),
    ("Genel", "Bir kafede menü standardizasyonu neyi sağlar?", "Pahalılık", "Yavaşlık", "Her seferinde aynı kalite", "Karışıklık", "C"),
    ("Genel", "'Seasonality' (mevsimsellik) kahvede neyi ifade eder?", "Kışın içilmesi", "Tazelik için hasat dönemine dikkat", "Yazın içilmesi", "Renk", "B"),
    ("Genel", "Kahve menşe etiketinde sık görülen bilgi nedir?", "Ülke/bölge, çiftlik, işleme, çeşit", "Sadece fiyat", "Sadece marka", "Sadece renk", "A"),
    ("Genel", "İyi bir kahve deneyimi için en temel üçlü nedir?", "Büyük bardak", "Taze çekirdek, doğru öğütme, doğru demleme", "Soğuk süt", "Bol şeker", "B"),
    ("Demleme", "Türk kahvesinde 'pişirme köpüğü' kaçırılırsa ne olur?", "Renk maviye döner", "Sunum kalitesi düşer", "Kafein artar", "Tat tuzlanır", "B"),
    ("Demleme", "Espresso için ideal su sıcaklığı yaklaşık nedir?", "60°C", "90-95°C", "40°C", "100°C kaynar", "B"),
    ("Demleme", "Cold brew ile iced coffee (buzlu kahve) farkı nedir?", "Fark yok", "İkisi de kaynatılır", "Aynıdır", "Cold brew soğuk demlenir; iced coffee sıcak demlenip soğutulur", "D"),
    ("Demleme", "V60 filtresini ıslatmanın (rinse) amacı nedir?", "Süs", "Ağırlık", "Kağıt tadını gidermek ve ısıtmak", "Renk", "C"),
    ("Demleme", "Espresso çekiminde 'pre-infusion' nedir?", "Soğutmak", "Öğütmek", "Düşük basınçla ön ıslatma", "Süt eklemek", "C"),
    ("Demleme", "Demleme oranını ölçmek için en pratik araç nedir?", "Termometre tek başına", "Renk kartı", "Cetvel", "Terazi", "D"),
    ("Espresso", "Süt köpüğü 'latte art' için fazla kalınsa ne olur?", "Kafein artar", "Daha iyi olur", "Desen oturmaz/zorlaşır", "Renk değişir", "C"),
    ("Espresso", "Cappuccino'da klasik oran yaklaşık nedir?", "Tamamı espresso", "Tamamı süt", "1/3 espresso, 1/3 süt, 1/3 köpük", "Yarı su", "C"),
    ("Espresso", "Espresso'nun 'sweet spot' (en lezzetli an) için ne kritiktir?", "Bol şeker", "Soğukluk", "Doğru öğütme+doz+süre dengesi", "Büyük bardak", "C"),
    ("Espresso", "Steam wand'ı süt içinde derin tutmak neye yol açar?", "Patlama", "Soğuma", "Çok köpük", "Köpüksüz, sadece ısınma", "D"),
    ("Çekirdek", "'Cascara' nedir?", "Çekirdek türü", "Süt çeşidi", "Makine", "Kurutulmuş kahve kirazı kabuğundan yapılan içecek", "D"),
    ("Çekirdek", "Kahve kirazının olgunlaşmadan toplanması tada ne yapar?", "Daha tatlı", "Otsu/sert ve düşük tatlılık", "Etkisiz", "Çiçeksi", "B"),
    ("Çekirdek", "'Anaerobic' işleme nedir?", "Kavurma türü", "Oksijensiz ortamda fermantasyon", "Öğütme", "Güneşte kurutma", "B"),
    ("Tarih", "Kahvenin 'şeytan içeceği' denip sonra kabul gördüğü kıta neresidir?", "Avustralya", "Avrupa", "Okyanusya", "Antarktika", "B"),
    ("Tarih", "Endonezya'nın ünlü kahve adalarından biri hangisidir?", "Sumatra", "Malta", "Kıbrıs", "Sicilya", "A"),
    ("Tarih", "Orta Amerika'da kahvesiyle ünlü ülkelerden biri hangisidir?", "Guatemala", "Finlandiya", "İzlanda", "Norveç", "A"),
    ("Kavurma", "Kavurmada 'development time' neyi etkiler?", "Fiyatı", "Ağırlığı", "Asitlik-tatlılık dengesini", "Sadece rengi", "C"),
    ("Kavurma", "Aynı çekirdek daha açık kavrulursa kafein kabaca nasıl olur?", "Sıfırlanır", "Yok olur", "On katına çıkar", "Belirgin biçimde değişmez (yaygın inanışın aksine)", "D"),
    ("Duyusal", "Espresso'da 'tactile/gövde' eksikse olası neden nedir?", "Çok süt", "Yetersiz ekstraksiyon/az doz", "Soğukluk", "Aşırı doz", "B"),
    ("Duyusal", "Kahvede 'fermented/aşırı fermente' tat genelde nasıl algılanır?", "Tatlı çikolata", "Tuzlu", "İstenmeyen, bozuk/alkolsü", "Hoş çiçeksi", "C"),
    ("Ekipman", "Espresso makinesinde 'group gasket' aşınırsa ne olur?", "Renk değişir", "Süt köpüğü artar", "Daha iyi crema", "Kaçak/çekim sorunları", "D"),
    ("Ekipman", "Öğütücü bıçakları (burr) körelirse ne olur?", "Daha iyi tat", "Daha hızlı", "Etkisiz", "Eşitsiz öğütme ve kötü tat", "D"),
    ("Sektör", "Bir kafede 'spec/reçete kartı' neyi içerir?", "Müşteri adları", "Fiyat indirimi", "Müzik listesi", "Doz, su, süre, sıcaklık gibi standartlar", "D"),
    ("Sektör", "Süt buharlama sonrası sürahi nasıl bırakılmalı?", "Sütlü haliyle", "Sıcakta açık", "Devrik", "Temizlenip durulanmış", "D"),
    ("Sektör", "Allerjisi olan müşteriye en doğru yaklaşım nedir?", "Tahmin etmek", "İçeriği net bilmek ve bilgilendirmek", "Acele etmek", "Görmezden gelmek", "B"),
    ("Kültür", "'Doppio' kaç shot espresso'dur?", "Yarım", "2", "1", "3", "B"),
    ("Kültür", "'Café crème' hangi ülkede yaygın bir terimdir?", "Brezilya", "Fransa/İsviçre", "Hindistan", "Japonya", "B"),
    ("Genel", "Kahve dünyasında 'q grader' kimdir?", "Kahve kalitesini puanlayan sertifikalı uzman", "Garson", "Çiftçi", "Kasiyer", "A"),
    ("Genel", "Bir bardak filtre kahvenin yaklaşık ne kadarı sudur?", "%98+", "%10", "%50", "%70", "A"),
    ("Genel", "Espresso'da hedeflenen denge nedir?", "Sadece acılık", "Tatlılık-asitlik-acılık uyumu", "Sadece su", "Sadece tatlılık", "B"),
    ("Genel", "Sürdürülebilir kafede tek kullanımlık atığı azaltmak için ne yapılır?", "Çift paket", "Daha çok plastik", "Hiçbir şey", "Tekrar kullanılabilir bardak teşviki", "D"),
]
