from django.urls import path
from . import views

urlpatterns = [
    path('manifest.webmanifest', views.pwa_manifest, name='pwa_manifest'),
    path('sw.js', views.pwa_service_worker, name='pwa_sw'),
    path('icons/<str:ad>', views.pwa_icon, name='pwa_icon'),
    path('', views.ana_sayfa, name='ana_sayfa'),
    path('puantaj/', views.puantaj_sayfa, name='puantaj'),
    path('mola/', views.mola_sayfa, name='mola'),
    path('ozet/', views.gosterge, name='gosterge'),
    path('yedekler/', views.yedekler, name='yedekler'),
    path('bildirimler/', views.bildirimler, name='bildirimler'),
    path('bildirim/<int:bid>/oku/', views.bildirim_oku, name='bildirim_oku'),
    path('yedekler/indir/<str:ad>/', views.yedek_indir, name='yedek_indir'),
    path('ekip/', views.ekip_sayfa, name='ekip'),
    path('gunluk-soru/', views.gunluk_soru, name='gunluk_soru'),
    path('bilgi-karnesi/', views.bilgi_karnesi, name='bilgi_karnesi'),
    path('soru-yonetimi/', views.soru_yonetimi, name='soru_yonetimi'),
    path('puantaj/excel/', views.puantaj_excel_export, name='puantaj_excel_export'),
    path('zayi/', views.zayi_sayfa, name='zayi'),
    path('zayi/excel/', views.zayi_excel_export, name='zayi_excel_export'),
    path('sevkiyat/', views.sevkiyat_sayfa, name='sevkiyat'),
    path('sevkiyat-duzenle/', views.sevkiyat_duzenle, name='sevkiyat_duzenle'),
    path('sevkiyat/<int:talep_id>/belge/<str:tip>/', views.sevkiyat_belge, name='sevkiyat_belge'),
    path('sevkiyat/<int:talep_id>/excel/', views.sevkiyat_excel, name='sevkiyat_excel'),
    path('sevkiyat/kalem/hazirla/', views.sevkiyat_kalem_hazirla, name='sevkiyat_kalem_hazirla'),
    path('kalibrasyon/', views.kalibrasyon_sayfa, name='kalibrasyon'),
    path('irsaliye/', views.irsaliye_sayfa, name='irsaliye'),
    path('stok/', views.stok_sayimi, name='stok'),
    path('stok/excel/', views.stok_excel, name='stok_excel'),
    path('stok-duzenle/', views.stok_duzenle, name='stok_duzenle'),
    path('kvkk/', views.kvkk, name='kvkk'),
    path('kullanim-kosullari/', views.kullanim_kosullari, name='kullanim_kosullari'),
    path('gizlilik/', views.gizlilik, name='gizlilik'),
]
